### ISSUE TITLE
ReferenceError: WASM is not defined

### ISSUE THREAD

**Issue by cierniak** [WebAssembly/wasm-e2e#16]
When I try to run the hello.c example, I'm getting this error:

```
$ ./scripts/run.py test/hello.c
WebAssembly/wasm-e2e/test/wasm.js:46: ReferenceError: WASM is not defined
m = WASM.instantiateModule(readbuffer(arguments[0]), ffi);
    ^
ReferenceError: WASM is not defined
    at WebAssembly/wasm-e2e/test/wasm.js:46:5
```

**Comment by binji** [comment]
since v8-native-prototype merged upstream with v8, it requires an additional flag `--expose-wasm`. I've added it to sexpr-wasm-prototype, but it seems it hasn't been added here.

**Comment by cierniak** [comment]
I'm not sure what the procedure for getting this fixed is. I have created a pull request with a fix suggested by you: https://github.com/WebAssembly/wasm-e2e/pull/17
How do I get someone to look at it or produce an alternative fix if they don't like mine?

**Comment by cierniak** [comment]
Recent changes make it break with the same error.

**Comment by binji** [comment]
Yeah, it was recently renamed from `WASM`to `_WASMEXP_`.

**Comment by cierniak** [comment]
Thanks for the tip! PR #20 created.
