### ISSUE TITLE
Make run.py accept .wast files as input

### ISSUE THREAD

**Issue by cierniak** [WebAssembly/wasm-e2e#19]
The `run.py` script is a very convenient way to compile a C file and run it. I would like to propose modifying the script, so that it can also accept .wast files as input and run them, so that it can be used to test WASM files written or tweaked by hand.

This would be a very simple change and I can create a PR for this.

**Comment by binji** [comment]
Sounds good to me.

**Comment by cierniak** [comment]
A quick update: I have merged with the new changes to wasm-e2e and I am now blocked by the fact that binaryen doesn't build on my system (MacOS). Once I figure out how to make binaryen build, I will send a PR.
